name: publish-and-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-firefox:
    name: Build & publish Firefox extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup web-ext
      run: make setup

    - name: Build Firefox extension
      run: make build

    - name: Publish to AMO
      run: make publish-ff-ci
      env:
        AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
        AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}

    - name: Upload .xpi as artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: web-ext-artifacts/*.xpi

  publish-chrome:
    name: Build & publish Chrome extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create archive
      run: zip -r Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip . -x '*.git/*' '*.env' '*.amo-upload-uuid' '*web-ext-artifacts/*' '*dist/*' '*images/screenshot-*.png'

    - name: Upload & publish
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        extension-id: jcjolbklpgfkleemmoohlbmjoheibmjc
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        file-path: Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip
        publish: true

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [publish-firefox, publish-chrome]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create archive
      run: zip -r Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip . -x '*.git/*' '*.env' '*.amo-upload-uuid' '*web-ext-artifacts/*' '*dist/*' '*images/screenshot-*.png'

    - name: Download Firefox artifact
      uses: actions/download-artifact@v4
      with:
        name: firefox-extension
        path: web-ext-artifacts

    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Overseerr Assistant ${{ env.RELEASE_VERSION }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          Overseerr-Assistant_${{ env.RELEASE_VERSION }}.zip
          web-ext-artifacts/*.xpi
